# Top-level configuration
name = "blockspace-web"
main = "./src/index.ts"
compatibility_date = "2023-12-01"

workers_dev = false
route = { pattern = "blockspace.so/*", zone_name = "blockspace.so" }

[env.staging]
name = "blockspace-staging"
route = { pattern = "staging.blockspace.so/*", zone_name = "blockspace.so" }


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "blockspace"
database_id = "cf1e29f8-9d84-4e6d-8114-ddd25f8489a4"