import './globals.css';
import { BaseProvider } from './providers';
import '@solana/wallet-adapter-react-ui/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NavBar } from '@/src/components/nav-bar';

import '@dialectlabs/react-ui/index.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background text-foreground`}>
        <BaseProvider>
          <NavBar />
          <main className="mb-20">{children}</main>
        </BaseProvider>
      </body>
    </html>
  );
}
